# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aphw-ddi-compensation-scheme:
    build:
      target: development
    image: aphw-ddi-compensation-scheme-development
    container_name: aphw-ddi-compensation-scheme-development
    ports:
      - "3009:3000"
      - "9239:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://aphw-ddi-compensation-scheme-azurite:10000/devstoreaccount1;}
    depends_on:
      - aphw-ddi-compensation-scheme-azurite

  aphw-ddi-compensation-scheme-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
  azurite_data:
