{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-compensation-scheme.container-secret") -}}
{{- define "aphw-ddi-compensation-scheme.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  COOKIE_PASSWORD: {{ quote .Values.container.cookiePassword }}
  REDIS_PASSWORD: {{ quote .Values.container.redisPassword }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  {{- end }}
{{- end -}}
