environment: production
environmentCode:
name: aphw-ddi-compensation-scheme
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-compensation-scheme

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: aphw-ddi-compensation-scheme-config-map

containerSecret:
  name: aphw-ddi-compensation-scheme-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  cookiePassword: cookiecookiecookiecookiecookiecookie
  redisHostname: redis-hostname.default
  redisPartition: aphw-ddi-compensation-scheme
  redisPassword: redis
  redisPort: 6379
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageAccountName: dummy

ingress:
  class: nginx
  endpoint: aphw-ddi-compensation-scheme
  server: value.replaced.from.app.config

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
